name: Deploy (Vercel + Smoke)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Production Deploy
        run: |
          if [ -z "${{ secrets.VERCEL_DEPLOY_HOOK_PROD }}" ]; then
            echo "::error ::Missing secret VERCEL_DEPLOY_HOOK_PROD"
            exit 1
          fi
          curl -fsS -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_PROD }}"
      - name: Wait for deployment to complete
        run: sleep 60
      - name: Smoke test /api/smoke
        run: |
          if [ -z "${{ secrets.PLAY_URL }}" ]; then
            echo "::error ::Missing secret PLAY_URL"
            exit 1
          fi
          echo "Pinging: ${{ secrets.PLAY_URL }}/api/smoke"
          HTTP=$(curl -s -o /tmp/out.json -w "%{http_code}" "${{ secrets.PLAY_URL }}/api/smoke")
          echo "HTTP $HTTP"
          cat /tmp/out.json || true
          if [ "$HTTP" != "200" ]; then
            echo "::error ::Smoke test failed"
            exit 1
          fi
